#! /bin/bash

git clone https://github.com/fizyr/keras-retinanet
cd keras-retinanet
pip3 install . --user
cd snapshots
wget https://github.com/fizyr/keras-retinanet/releases/download/0.4.1/resnet50_coco_best_v2.1.0.h5
cd ../examples