#! /bin/bash

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y gcc
sudo apt-get purge nvidia* 
sudo add-apt-repository -y ppa:graphics-drivers
sudo apt-get update 
sudo apt-get install -y nvidia-396 nvidia-modprobe
sudo reboot